In [1]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Mounted at /content/gdrive


In [2]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [3]:
#membuat matrix 2*2, yang isinya 1234
const_a=tf.constant([[1,2,3,4]], shape=[2,2],dtype=tf.float32)
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [4]:
zeros_b=tf.zeros(shape=[2,3],dtype=tf.int32)
zeros_b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [5]:
zeros_like_c=tf.zeros_like(const_a)
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [6]:
fill_d=tf.fill([3,3],8)
fill_d.numpy()

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [7]:
random_e=tf.random.normal([5,5],mean=0,stddev=1.0,seed=1)
random_e.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [8]:
random_e=tf.random.normal([5,5],mean=0,stddev=1.0,seed=1)
random_e.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

In [9]:
list_f=[1,2,3,4,5,6]
type(list_f)

list

In [10]:
tensor_f=tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [11]:
var_1=tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
print("value dari var_1:",var_1.read_value())
var_value_1=[[1,2,3],[4,5,6]]
var_1.assign(var_value_1)
print("value var1 setelah di tambah:",var_1.read_value())

value dari var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
value var1 setelah di tambah: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [13]:
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [14]:
tensor_h=tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.31005132e+00, -1.36065769e+00,  2.88896620e-01],
         [ 1.55255282e+00,  7.58763909e-01, -4.29963678e-01],
         [-7.91817725e-01, -7.57710814e-01, -3.73638600e-01],
         ...,
         [ 2.70775169e-01,  1.03833699e+00, -4.93258774e-01],
         [ 6.52586520e-01, -1.00927305e+00,  4.97718006e-01],
         [ 1.83592606e+00, -5.33052027e-01,  1.57950211e+00]],

        [[ 8.43427122e-01,  5.06313443e-01,  2.31535509e-01],
         [-1.21022105e+00,  2.25434732e+00, -6.57950103e-01],
         [ 9.73594248e-01,  4.27695513e-01,  3.90376687e-01],
         ...,
         [ 2.69023061e-01, -1.70968640e+00, -1.14311361e+00],
         [-2.76065111e+00,  1.58666551e+00,  1.25299990e+00],
         [ 4.54780996e-01,  1.62249207e-01, -3.55557740e-01]],

        [[-2.76593029e-01,  9.86272022e-02,  8.76967490e-01],
         [ 1.37395453e+00, -8.98318172e-01,  1.50393188e+00],
         [ 2.23251724e+00,  1.73982358e+00

In [15]:
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[ 1.3100513 , -1.3606577 ,  0.28889662],
        [ 1.5525528 ,  0.7587639 , -0.42996368],
        [-0.7918177 , -0.7577108 , -0.3736386 ],
        ...,
        [ 0.27077517,  1.038337  , -0.49325877],
        [ 0.6525865 , -1.009273  ,  0.497718  ],
        [ 1.835926  , -0.533052  ,  1.5795021 ]],

       [[ 0.8434271 ,  0.50631344,  0.23153551],
        [-1.210221  ,  2.2543473 , -0.6579501 ],
        [ 0.97359425,  0.4276955 ,  0.3903767 ],
        ...,
        [ 0.26902306, -1.7096864 , -1.1431136 ],
        [-2.760651  ,  1.5866655 ,  1.2529999 ],
        [ 0.454781  ,  0.16224921, -0.35555774]],

       [[-0.27659303,  0.0986272 ,  0.8769675 ],
        [ 1.3739545 , -0.8983182 ,  1.5039319 ],
        [ 2.2325172 ,  1.7398236 ,  0.7914075 ],
        ...,
        [ 0.6980913 , -0.12071318, -0.18323784],
        [-0.9579426 ,  0.6694387 ,  1.2367368 ],
        [ 0.18545717,  0.6838318 , -0.19977154]],

       ...,

     

In [16]:
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-4.63074893e-01,  1.54804087e+00, -3.85994375e-01],
         [-1.24308920e+00,  4.62918103e-01,  5.43261409e-01],
         [ 2.77718306e-01,  3.57393324e-01,  1.05955899e+00],
         ...,
         [ 6.17177710e-02,  9.59328637e-02, -5.52243352e-01],
         [ 1.52416170e-01,  1.36120272e+00,  1.49381012e-01],
         [ 1.13954231e-01,  5.67696989e-01, -1.45757711e+00]],

        [[-1.03920400e+00, -2.41267323e-01, -3.18185359e-01],
         [ 5.04191875e-01,  8.59422423e-03, -4.66526210e-01],
         [-2.40494519e-01,  4.54926163e-01, -7.26716757e-01],
         ...,
         [ 1.31297147e+00,  1.72172189e+00, -9.29408893e-02],
         [-5.97385824e-01,  4.69144434e-01,  2.56231993e-01],
         [ 4.50755030e-01,  7.98269883e-02, -7.51838237e-02]],

        [[-1.19674361e+00,  1.46346524e-01, -3.55298817e-01],
         [ 9.37539041e-01,  5.44378579e-01, -5.02968073e-01],
         [-8.75575960e-01,  1.99874055e+00

In [17]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.49885556>

In [18]:
indices=[0,1,3]
tf.gather(tensor_h,axis=0,indices=indices,batch_dims=1)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[ 1.3100513e+00, -1.3606577e+00,  2.8889662e-01],
         [ 1.5525528e+00,  7.5876391e-01, -4.2996368e-01],
         [-7.9181772e-01, -7.5771081e-01, -3.7363860e-01],
         ...,
         [ 2.7077517e-01,  1.0383370e+00, -4.9325877e-01],
         [ 6.5258652e-01, -1.0092731e+00,  4.9771801e-01],
         [ 1.8359261e+00, -5.3305203e-01,  1.5795021e+00]],

        [[ 8.4342712e-01,  5.0631344e-01,  2.3153551e-01],
         [-1.2102211e+00,  2.2543473e+00, -6.5795010e-01],
         [ 9.7359425e-01,  4.2769551e-01,  3.9037669e-01],
         ...,
         [ 2.6902306e-01, -1.7096864e+00, -1.1431136e+00],
         [-2.7606511e+00,  1.5866655e+00,  1.2529999e+00],
         [ 4.5478100e-01,  1.6224921e-01, -3.5555774e-01]],

        [[-2.7659303e-01,  9.8627202e-02,  8.7696749e-01],
         [ 1.3739545e+00, -8.9831817e-01,  1.5039319e+00],
         [ 2.2325172e+00,  1.7398236e+00,  7.9140753e-01],
         ...,
         [ 

In [19]:
indices=[[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.210221 , -1.2633808], dtype=float32)>

In [20]:
const_d_1=tf.constant([[1,2,3,4]],shape=[2,2],dtype=tf.float32)
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


In [21]:
reshape_1=tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1,(3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [22]:
expand_sample_1=tf.random.normal([100,100,3],seed=1)
print("size of the original data:",expand_sample_1.shape)
print("tambah dimensi sebelum dimensi 1:",tf.expand_dims(expand_sample_1,axis=0).shape)
print("add dimension sebelum dimensi 2:",tf.expand_dims(expand_sample_1,axis=1).shape )

size of the original data: (100, 100, 3)
tambah dimensi sebelum dimensi 1: (1, 100, 100, 3)
add dimension sebelum dimensi 2: (100, 1, 100, 3)


In [23]:
squeeze_sample_1=tf.random.normal([1,100,100,3])
print("size dari original data:",squeeze_sample_1.shape)
squeeze_sample_1=tf.squeeze(expand_sample_1)
print("data ukuran setelah di squueze:",squeeze_sample_1.shape)

size dari original data: (1, 100, 100, 3)
data ukuran setelah di squueze: (100, 100, 3)


In [24]:
trans_sample_1=tf.constant([1,2,3,4,5,6],shape=[2,3])
print("ukuran data original:",trans_sample_1.shape)
transposed_sample_1=tf.transpose(trans_sample_1)
print("ukuran setelah di transpose:",transposed_sample_1.shape)

ukuran data original: (2, 3)
ukuran setelah di transpose: (3, 2)


In [25]:
trans_sample2=tf.random.normal([4,100,200,3])
print("ukuran data original:",trans_sample2.shape)
transposed_sample2=tf.transpose(trans_sample2,[0,2,1,3])
print("ukuran data setelah di transpose:",transposed_sample2.shape)

ukuran data original: (4, 100, 200, 3)
ukuran data setelah di transpose: (4, 200, 100, 3)


In [26]:
bc_sample1=tf.constant([1,2,3,4,5,6])
print("original data:",bc_sample1.numpy())
bc_hasil=tf.broadcast_to(bc_sample1,shape=[4,6])
print("hasil bc:",bc_hasil.numpy())

original data: [1 2 3 4 5 6]
hasil bc: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [27]:
a=tf.constant([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=tf.constant([1,2,3])
print(a+b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


In [28]:
a=tf.constant([[3,5],[4,8]])
b=tf.constant([[1,6],[2,9]])
print(tf.add(a,b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


In [29]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>

In [30]:
argmax_sample_1=tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor:",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1,axis=0)
max_sample_2 = tf.argmax(argmax_sample_1,axis=1)
print("locate maximum value by column:",max_sample_1.numpy())
print("locate maximum value by row:",max_sample_2.numpy())

input tensor: [[1 3 2]
 [2 5 8]
 [7 5 9]]
locate maximum value by column: [2 1 2]
locate maximum value by row: [1 2 2]


In [31]:
reduce_sample_1=tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())
print("kalkulasi hasil semua elemen di tensor:",tf.reduce_sum(reduce_sample_1,axis=None).numpy())

original data [[1 2 3]
 [4 5 6]]
kalkulasi hasil semua elemen di tensor: 21


In [32]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("size dari original data:",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1=tf.concat([concat_sample_1,concat_sample_2],axis=0)

size dari original data: (4, 100, 100, 3) (40, 100, 100, 3)


In [33]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("size dari original data:", stack_sample_1.shape,stack_sample_2.shape)
stacked_sample_1=tf.stack([stack_sample_1,stack_sample_2],axis=0)
print("size dari data di gabung:",stacked_sample_1.shape)

size dari original data: (100, 100, 3) (100, 100, 3)
size dari data di gabung: (2, 100, 100, 3)


In [34]:
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-9.8995402e-02,  5.2207458e-01,  1.1110460e+00],
         [-1.3435725e+00,  1.6025778e+00, -4.1876501e-01],
         [-1.2836680e-01,  4.4143054e-01,  4.2514494e-01],
         ...,
         [ 6.3776505e-01, -5.1506853e-01,  1.3321468e+00],
         [-1.2564907e+00, -2.1263646e-01,  6.3600105e-01],
         [-8.5750240e-01, -7.4819791e-01, -1.0136235e+00]],
 
        [[ 6.3378733e-01,  2.5643119e-01,  2.0661113e+00],
         [ 1.4321696e+00, -1.9961253e-01,  3.7661630e-01],
         [-3.7621769e-01,  1.8784374e+00,  8.6916393e-01],
         ...,
         [-7.2633034e-01,  3.5065490e-01,  7.6410645e-01],
         [-1.3093703e+00,  2.6933982e+00, -6.5998977e-01],
         [-8.6252385e-01, -1.2363861e+00,  2.3721437e-01]],
 
        [[ 2.1064867e-01,  4.9525625e-01, -3.0876666e-01],
         [-9.7736406e-01,  5.6815886e-01,  4.3556464e-01],
         [-2.0062892e+00,  1.0362862e+00, -1.0306730e+00],
         ...,
         [ 

In [35]:
import numpy as np
split_sample_1=tf.random.normal([10,100,100,3])
print("size dari original data:",split_sample_1.shape)
splited_sample_1=tf.split(split_sample_1,num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_split set to 10:",np.shape(splited_sample_1))
splited_sample_2=tf.split(split_sample_1,num_or_size_splits=[3,5,2],axis=0)
print("ketika di split, ukuran datanya:",np.shape(splited_sample_2[0]),np.shape(splited_sample_2[1]),np.shape(splited_sample_2[2]))

size dari original data: (10, 100, 100, 3)
size of the split data when m_or_size_split set to 10: (5, 2, 100, 100, 3)
ketika di split, ukuran datanya: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [36]:
sort_sample_1=tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())
sorted_sample_1=tf.sort(sort_sample_1,direction="ASCENDING")
print("tensor di sorting berdasarkan ascending:",sorted_sample_1.numpy())
sorted_sample_2=tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elemen tensor yang di ascending: ",sorted_sample_2.numpy())

input tensor: [3 6 2 8 9 5 7 1 4 0]
tensor di sorting berdasarkan ascending: [0 1 2 3 4 5 6 7 8 9]
indexes of elemen tensor yang di ascending:  [9 7 2 0 8 5 1 6 3 4]


In [37]:
values,index=tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())
print("5 value pertama di escending:",values.numpy())
print("index dari 5 order ascending:",index.numpy())

input tensor: [3 6 2 8 9 5 7 1 4 0]
5 value pertama di escending: [9 8 7 6 5]
index dari 5 order ascending: [4 3 6 1 5]


In [38]:
x=tf.ones((2,2),dtype=tf.dtypes.float32)
y=tf.constant([[1,2],[3,4]],dtype=tf.dtypes.float32)
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [39]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
a=tf.ones((2,2),dtype=tf.dtypes.float32)
b=tf.constant([[1,2],[3,4]],dtype=tf.dtypes.float32)
c=tf.matmul(a,b)
with tf.Session() as sess:
  print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [40]:
import tensorflow as tf
thre_1 = tf.random.uniform([],0,1)
x = tf.reshape(tf.range(0,4),[2,2])
print(thre_1)
if thre_1.numpy()>0.5:
  y=tf.matmul(x,x)
else:
  y=tf.add(x,x)

Tensor("random_uniform/RandomUniform:0", shape=(), dtype=float32)


AttributeError: ignored

In [41]:
@tf.function
def simple_nn_layer(w,x,b):
  print(b)
  return tf.nn.relu(tf.matmul(w,x)+b)
w=tf.random.uniform((3,3))
x=tf.random.uniform((3,3))
b=tf.constant(0.5,dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor 'PartitionedCall:0' shape=(3, 3) dtype=float32>

In [42]:
import timeit
CNN_cell=tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))
@tf.function
def CNN_fn(image):
  return CNN_cell(image)
image=tf.zeros([100,200,200,3])
CNN_cell(image)
CNN_fn(image)
print("time required for performing the CNN",timeit.timeit(lambda:CNN_cell(image),number=10))
print("time required CNN graph mode:",timeit.timeit(lambda:CNN_fn(image),number=10))

time required for performing the CNN 0.02634213200008162
time required CNN graph mode: 0.010780538999824785


In [43]:
import tensorflow.keras.layers as layers
import tensorflow as tf
model = tf.keras.Sequential()
model.add(layers.Dense(32,activation='relu'))
model.add(layers.Dense(32,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))
x=tf.keras.Input(shape=32)
h1=layers.Dense(32,activation='relu')(x)
h2=layers.Dense(32,activation='relu')(h1)
y=layers.Dense(10,activation='softmax')(h2)
model_sample_2=tf.keras.models.Model(x,y)
model_sample_2.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_4 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                330       
Total params: 2,442
Trainable params: 2,442
Non-trainable params: 0
_________________________________________________________________


In [57]:
layers.Dense(32,kernel_initializer=tf.keras.initializers.he_normal)
layers.Dense(32,kernel_regularizer=tf.keras.regularizers.l2(0.01))

In [45]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

In [46]:
layers.MaxPooling2D(pool_size=(2,2),strides=(2,1))

In [65]:
import numpy as np
inputs=tf.keras.Input(shape=(3,1))
lstm=layers.LSTM(1,return_sequences=True)(inputs)
model1=tf.keras.models.Model(inputs=inputs,outputs=lstm)
inputs=tf.keras.Input(shape=(3,1))
lstm=layers.LSTM(1,return_sequences=False)(inputs)
model2=tf.keras.models.Model(inputs=inputs,outputs=lstm)

data=[[[0.1],[0.2],[0.3]]]
print(data)
print("data True:",model1.predict(data))
print("data False:",model2.predict(data))

[[[0.1], [0.2], [0.3]]]


ValueError: ignored

In [48]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),loss=tf.keras.losses.categorical_crossentropy,
              metrics=[tf.keras.metrics.categorical_accuracy])

In [49]:
import numpy as np

train_x=np.random.random((1000,36))
train_y=np.random.random((1000,10))
val_x=np.random.random((200,36))
val_y=np.random.random((200,10))
model.fit(train_x,train_y,epochs=10,batch_size=100,validation_data=(val_x,val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 0s 266us/sample - loss: 11.6153 - categorical_accuracy: 0.0980 - val_loss: 11.6530 - val_categorical_accuracy: 0.1050
Epoch 2/10
1000/1000 [==============================] - 0s 22us/sample - loss: 11.6537 - categorical_accuracy: 0.1170 - val_loss: 11.7491 - val_categorical_accuracy: 0.1250
Epoch 3/10
1000/1000 [==============================] - 0s 18us/sample - loss: 11.8155 - categorical_accuracy: 0.1080 - val_loss: 12.0270 - val_categorical_accuracy: 0.1250
Epoch 4/10
1000/1000 [==============================] - 0s 20us/sample - loss: 12.2618 - categorical_accuracy: 0.1110 - val_loss: 12.7229 - val_categorical_accuracy: 0.1250
Epoch 5/10
1000/1000 [==============================] - 0s 19us/sample - loss: 13.2804 - categorical_accuracy: 0.1110 - val_loss: 14.1882 - val_categorical_accuracy: 0.1250
Epoch 6/10
 100/1000 [==>...........................] - ETA: 0s - loss: 13.9601 - categ

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:2426: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '


1000/1000 [==============================] - 0s 32us/sample - loss: 15.0388 - categorical_accuracy: 0.1110 - val_loss: 16.1403 - val_categorical_accuracy: 0.1250
Epoch 7/10
1000/1000 [==============================] - 0s 23us/sample - loss: 16.9626 - categorical_accuracy: 0.1110 - val_loss: 18.2614 - val_categorical_accuracy: 0.1250
Epoch 8/10
1000/1000 [==============================] - 0s 20us/sample - loss: 19.9275 - categorical_accuracy: 0.1130 - val_loss: 22.5628 - val_categorical_accuracy: 0.1250
Epoch 9/10
1000/1000 [==============================] - 0s 24us/sample - loss: 25.0922 - categorical_accuracy: 0.1150 - val_loss: 28.7753 - val_categorical_accuracy: 0.1250
Epoch 10/10
1000/1000 [==============================] - 0s 26us/sample - loss: 31.9607 - categorical_accuracy: 0.1130 - val_loss: 36.5599 - val_categorical_accuracy: 0.1350


In [50]:
dataset = tf.data.Dataset.from_tensor_slices((train_x,train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset=tf.data.Dataset.from_tensor_slices((val_x,val_y))
val_dataset=val_dataset.batch(32)
model.fit(dataset,epochs=10, steps_per_epoch=30,
          validation_data=val_dataset,validation_steps=3)

Train on 30 steps, validate on 3 steps
Epoch 1/10
30/30 [==============================] - 0s 5ms/step - batch: 14.5000 - size: 1.0000 - loss: 50.7266 - categorical_accuracy: 0.1052 - val_loss: 67.7604 - val_categorical_accuracy: 0.1562
Epoch 2/10
30/30 [==============================] - 0s 1ms/step - batch: 14.5000 - size: 1.0000 - loss: 87.9144 - categorical_accuracy: 0.1047 - val_loss: 110.6007 - val_categorical_accuracy: 0.1458
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - batch: 14.5000 - size: 1.0000 - loss: 135.8307 - categorical_accuracy: 0.1100 - val_loss: 163.6948 - val_categorical_accuracy: 0.1562
Epoch 4/10
30/30 [==============================] - 0s 1ms/step - batch: 14.5000 - size: 1.0000 - loss: 196.0278 - categorical_accuracy: 0.1154 - val_loss: 228.3651 - val_categorical_accuracy: 0.1458
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - batch: 14.5000 - size: 1.0000 - loss: 266.0044 - categorical_accuracy: 0.1132 - val_loss: 304.8902

In [61]:
import os
Epochs = 10
logdir=os.path.join("logs")
if not os.path.exists(logdir):
  os.mkdir(logdir)
def lr_Scheduler(epoch):
  if epoch>0.9*Epochs:
    lr=0.00001
  elif epoch>0.5*Epochs:
    lr=0.0001
  elif epoch>0.25*Epochs:
    lr=0.01
  else:
    lr=0.1
  print(lr)
  return lr

callbacks=[tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',min_delta=1e-2,patience=2),tf.keras.callbacks.ModelCheckpoint(
        filepath='testmodel_{epoch}.h5',save_best_only=True,monitor='val_loss'),
        tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),
        tf.keras.callbacks.TensorBoard(log_dir=logdir)]
model.fit(train_x,train_y,batch_size=16,epochs=Epochs,callbacks=callbacks,validation_data=(val_x,val_y))

Train on 1000 samples, validate on 200 samples
0.1
Epoch 1/10
1000/1000 [==============================] - 0s 223us/sample - loss: 21806092.8640 - categorical_accuracy: 0.1140 - val_loss: 32743059.6800 - val_categorical_accuracy: 0.0600 - lr: 0.1000
0.1
Epoch 2/10
1000/1000 [==============================] - 0s 117us/sample - loss: 28218112.5280 - categorical_accuracy: 0.0980 - val_loss: 28440693.2800 - val_categorical_accuracy: 0.1100 - lr: 0.1000
0.1
Epoch 3/10
1000/1000 [==============================] - 0s 86us/sample - loss: 45268461.5360 - categorical_accuracy: 0.1060 - val_loss: 64452239.3600 - val_categorical_accuracy: 0.1100 - lr: 0.1000
0.01
Epoch 4/10
1000/1000 [==============================] - 0s 128us/sample - loss: 20722035.7720 - categorical_accuracy: 0.0920 - val_loss: 5001808.6000 - val_categorical_accuracy: 0.1100 - lr: 0.0100
0.01
Epoch 5/10
1000/1000 [==============================] - 0s 137us/sample - loss: 2997164.7240 - categorical_accuracy: 0.1070 - val_loss: 4

In [62]:
test_x=np.random.random((1000,36))
test_y=np.random.random((1000,10))
model.evaluate(test_x,test_y,batch_size=32)

[482839.1045, 0.09]

In [63]:
pre_x=np.random.random((10,36))
result=model.predict(test_x,)
print(result)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [1.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.5        0.         0.         ... 0.         0.         0.        ]
 [0.33333334 0.         0.         ... 0.         0.         0.        ]
 [0.5        0.         0.         ... 0.         0.         0.        ]]


In [66]:
import numpy as np
model.save('./model.the_save_model.h5')
new_model=tf.keras.models.load_model('./model/the_save_model.h5')
new_prediction=new_model.predict(test_x)
np.testing.assert_allclose(result,new_prediction,atol=1e-6)

OSError: ignored

In [ ]:
model.save_weights('./model/model_weights')
model.save_weights('./model/model_weights.h5')
model.load_weights('./model/model_weights')
model.load_weights('./model/model_weights.h5')

#Image recognition

In [ ]:
import tensorflow as tf
fashion_mnist=tf.keras.datasets.fashion_mnist
(train_X,train_y),(test_X,test_y)=fashion_mnist.load_data()

In [ ]:
from collections import Counter
len(Counter(train_y))


In [ ]:
import matplotlib.pyplot as plt
plt.imshow(train_X[3])

In [ ]:
train_label=tf.keras.utils.to_categorical(train_y,num_classes=10)
test_label=tf.keras.utils.to_categorical(test_y,num_classes=10)

In [ ]:
train_input=tf.data.Dataset.from_tensor_slices((train_X,train_label)).batch(50)
test_input=tf.data.Dataset.from_tensor_slices((test_X,test_label)).batch(50)

In [ ]:
input_data=tf.keras.Input([28,28])
dense=tf.keras.layers.Flatten()(input_data)

dense=tf.keras.layers.Dense(100,activation='relu')(dense)
dense=tf.keras.layers.Dense(100,activation='relu')(dense)
dense=tf.keras.layers.Dense(100,activation='relu')(dense)
dense=tf.keras.layers.Dense(100,activation='relu')(dense)

output_data=tf.keras.layers.Dense(10,activation='softmax')(dense)

In [ ]:
model=tf.keras.Model(inputs=input_data,outputs=outputs_data)

In [ ]:
model.compile(optimizer=tf.optimizers.Adam(0.001),
              loss=tf.losses.categorical_crossentropy,
              metrics=['accuracy'])

In [ ]:
model.summary()

In [ ]:
model.fit(train_input,epochs=10)

In [ ]:
model.evaluate(test_input)

In [ ]:
train_data=tf.expand_dims(train_X,-1)
test_data=tf.expand_dims(test_X,-1)

In [ ]:
train_input=tf.data.Dataset.from_tensor_slices((train_data,train_label)).batch(50)
test_input=tf.data.Dataset.from_tensor_slices((test_data,test_label)).batch(50)


In [ ]:
input_data=tf.keras.Input([28,28,1])


In [ ]:
conv=tf.keras.layers.Conv2D(30,5,padding='SAME',activation='relu')(input_data)
conv=tf.keras.layers.Conv2D(30,5,padding='SAME',activation='relu')(conv)

In [ ]:
conv=tf.keras.layers.MaxPool2D(strides=[2,2])(conv)
conv=tf.keras.layers.Conv2D(30,5,padding='SAME',activation='relu')(conv)

In [ ]:
dense=tf.keras.layers.Flatten()(conv)
output_data=tf.keras.layers.Dense(10,activation='relu')(dense)

In [ ]:
model=tf.keras.Model(inputs=input_data,outputs=output_data)
model.compile(optimizer=tf.optimizers.Adam(0.001),
              loss=tf.losses.categorical_crossentropy,
              metrics=['accuracy'])
model.summary()

In [ ]:
model.fit(train_input,epochs=1)
model.evaluate(test_input)

In [ ]:
model.save('./model.h5')

In [ ]:
modelx=tf.keras.models.load_model('./model.h5')
modelx=tf.rvaluate(test_input)